CREATE DATABASE freeswitch;
CREATE DATABASE fusionpbx;
CREATE ROLE root WITH SUPERUSER LOGIN PASSWORD 'psqlpass';
CREATE ROLE freeswitch WITH SUPERUSER LOGIN PASSWORD 'psqlpass';
CREATE ROLE fusionpbx WITH SUPERUSER LOGIN PASSWORD 'psqlpass';
GRANT ALL PRIVILEGES ON DATABASE freeswitch to freeswitch;
GRANT ALL PRIVILEGES ON DATABASE fusionpbx to fusionpbx;
GRANT ALL PRIVILEGES ON DATABASE freeswitch to fusionpbx;
CREATE USER fusionpbx WITH PASSWORD 'Peg@corn';